### ISSUE TITLE
能否提供多treatment的版本

### ISSUE THREAD

**Issue by ubhedc** [dgliu/KDD23_EFIN#1]
你好，看论文中是有多treatment的版本，当目前仓库里的代码似乎是二元treatment的，想问一下能否提供多treatment的版本供学习，感谢

**Comment by dgliu** [comment]
Hi, 多干预版本可以简捷地通过以下的方式来实现：

1. 假设当前有一个三干预的设置，那么每个干预对应的标签可以表示为[1, 0, 0], [0, 1, 0], [0, 0, 1]，在标签反转操作之后将变为[0, 1, 1], [1, 0, 1], [1, 1, 0]，然后将loss的计算更改为多类交叉熵即可，其余部分是不受影响的。

2. 可以遵循多分类问题转换为多个二分类问题的思想，将三干预的设置依次看做三个二值干预的设置，每个二值干预分别将第1类、第2类和第3类干预的标签视为0，其余视为0。在这种设置下，只需要使用当前版本的代码即可。
