### ISSUE TITLE
关于treatment的问题

### ISSUE THREAD

**Issue by hcz28** [dgliu/KDD23_EFIN#3]
老师您好，有两个问题想要咨询下哈：
1. intervention constraint module对treatment预测的label做inverse怎么理解呢？dragonnet论文里也有对propensity的预测，但应该是没有做inverse的
2. 在做预测时，treatment feature encoder的输入应该都是1，得到的才是对应的uplift吧（假如只有1种treatment的情况）？为什么代码里在做validation时输入的是真正的treatment？

**Comment by dgliu** [comment]
> 老师您好，有两个问题想要咨询下哈：
> 
> 1. intervention constraint module对treatment预测的label做inverse怎么理解呢？dragonnet论文里也有对propensity的预测，但应该是没有做inverse的
> 2. 在做预测时，treatment feature encoder的输入应该都是1，得到的才是对应的uplift吧（假如只有1种treatment的情况）？为什么代码里在做validation时输入的是真正的treatment？

感谢对我们工作的关注，以下是对应的回复：

1. intervention constraint module的设计动机基于一个直观的想法，即尽可能避免模型从X中推理出T的信息，从而缓解selection bias；先前的大多数方法的设计动机则是施加一个T的head作为额外监督，并在此基础上引入一些正则项来做t0和t1的balance，从而缓解selection bias。

2. uplift是y1-y0，treatment得分别取0和1，即所有treatment都要被考虑；我们写forward的时候让它同时提供了y1、y0和uplift，这样方便train和valid时都只需要调用一个forward，但请注意核对代码逻辑：真正的treatment的输入是为了在train时拿相应的预测y来计算loss，而在valid时所有样本都会取uplift（即所有treatment都会被考虑，拿到相应的所有预测y来计算uplift）。

**Comment by hcz28** [comment]
> > 老师您好，有两个问题想要咨询下哈：
> > 
> > 1. intervention constraint module对treatment预测的label做inverse怎么理解呢？dragonnet论文里也有对propensity的预测，但应该是没有做inverse的
> > 2. 在做预测时，treatment feature encoder的输入应该都是1，得到的才是对应的uplift吧（假如只有1种treatment的情况）？为什么代码里在做validation时输入的是真正的treatment？
> 
> 感谢对我们工作的关注，以下是对应的回复：
> 
> 1. intervention constraint module的设计动机基于一个直观的想法，即尽可能避免模型从X中推理出T的信息，从而缓解selection bias；先前的大多数方法的设计动机则是施加一个T的head作为额外监督，并在此基础上引入一些正则项来做t0和t1的balance，从而缓解selection bias。
> 2. uplift是y1-y0，treatment得分别取0和1，即所有treatment都要被考虑；我们写forward的时候让它同时提供了y1、y0和uplift，这样方便train和valid时都只需要调用一个forward，但请注意核对代码逻辑：真正的treatment的输入是为了在train时拿相应的预测y来计算loss，而在valid时所有样本都会取uplift（即所有treatment都会被考虑，拿到相应的所有预测y来计算uplift）。

感谢您的回复，又仔细看了代码，比较清楚了

**Comment by ubhedc** [comment]
> > 老师您好，有两个问题想要咨询下哈：
> > 
> > 1. intervention constraint module对treatment预测的label做inverse怎么理解呢？dragonnet论文里也有对propensity的预测，但应该是没有做inverse的
> > 2. 在做预测时，treatment feature encoder的输入应该都是1，得到的才是对应的uplift吧（假如只有1种treatment的情况）？为什么代码里在做validation时输入的是真正的treatment？
> 
> 感谢对我们工作的关注，以下是对应的回复：
> 
> 1. intervention constraint module的设计动机基于一个直观的想法，即尽可能避免模型从X中推理出T的信息，从而缓解selection bias；先前的大多数方法的设计动机则是施加一个T的head作为额外监督，并在此基础上引入一些正则项来做t0和t1的balance，从而缓解selection bias。
> 2. uplift是y1-y0，treatment得分别取0和1，即所有treatment都要被考虑；我们写forward的时候让它同时提供了y1、y0和uplift，这样方便train和valid时都只需要调用一个forward，但请注意核对代码逻辑：真正的treatment的输入是为了在train时拿相应的预测y来计算loss，而在valid时所有样本都会取uplift（即所有treatment都会被考虑，拿到相应的所有预测y来计算uplift）。

您好，想问一下，forward方法输出六个参数：c_logit, c_prob, c_tau, t_logit, t_prob, u_tau，这里面哪些是y1、y0和uplift呀，是不是c_logit是y0，t_logit是y1，u_tau是uplift，但我看c_logit+u_tau也不等于t_logit

**Comment by dgliu** [comment]
> > > 老师您好，有两个问题想要咨询下哈：
> > > 
> > > 1. intervention constraint module对treatment预测的label做inverse怎么理解呢？dragonnet论文里也有对propensity的预测，但应该是没有做inverse的
> > > 2. 在做预测时，treatment feature encoder的输入应该都是1，得到的才是对应的uplift吧（假如只有1种treatment的情况）？为什么代码里在做validation时输入的是真正的treatment？
> > 
> > 
> > 感谢对我们工作的关注，以下是对应的回复：
> > 
> > 1. intervention constraint module的设计动机基于一个直观的想法，即尽可能避免模型从X中推理出T的信息，从而缓解selection bias；先前的大多数方法的设计动机则是施加一个T的head作为额外监督，并在此基础上引入一些正则项来做t0和t1的balance，从而缓解selection bias。
> > 2. uplift是y1-y0，treatment得分别取0和1，即所有treatment都要被考虑；我们写forward的时候让它同时提供了y1、y0和uplift，这样方便train和valid时都只需要调用一个forward，但请注意核对代码逻辑：真正的treatment的输入是为了在train时拿相应的预测y来计算loss，而在valid时所有样本都会取uplift（即所有treatment都会被考虑，拿到相应的所有预测y来计算uplift）。
> 
> 您好，想问一下，forward方法输出六个参数：c_logit, c_prob, c_tau, t_logit, t_prob, u_tau，这里面哪些是y1、y0和uplift呀，是不是c_logit是y0，t_logit是y1，u_tau是uplift，但我看c_logit+u_tau也不等于t_logit

你好，c_logit是y0，u_tau是uplift，y1直接由y0+uplift获得（即c_logit+u_tau，见135行）；t_logit是倾向得分的预估，用于计算后续的约束项，见145行。你可以结合框架图再仔细理解一下每个分支的计算输出的含义。

**Comment by Weibin44** [comment]
> > 老师您好，有两个问题想要咨询下哈：
> > 
> > 1. intervention constraint module对treatment预测的label做inverse怎么理解呢？dragonnet论文里也有对propensity的预测，但应该是没有做inverse的
> > 2. 在做预测时，treatment feature encoder的输入应该都是1，得到的才是对应的uplift吧（假如只有1种treatment的情况）？为什么代码里在做validation时输入的是真正的treatment？
> 
> 感谢对我们工作的关注，以下是对应的回复：
> 
> 1. intervention constraint module的设计动机基于一个直观的想法，即尽可能避免模型从X中推理出T的信息，从而缓解selection bias；先前的大多数方法的设计动机则是施加一个T的head作为额外监督，并在此基础上引入一些正则项来做t0和t1的balance，从而缓解selection bias。
> 2. uplift是y1-y0，treatment得分别取0和1，即所有treatment都要被考虑；我们写forward的时候让它同时提供了y1、y0和uplift，这样方便train和valid时都只需要调用一个forward，但请注意核对代码逻辑：真正的treatment的输入是为了在train时拿相应的预测y来计算loss，而在valid时所有样本都会取uplift（即所有treatment都会被考虑，拿到相应的所有预测y来计算uplift）。

请问单单把label取反，0->1，1->0对机器来说有什么区别吗？
