### ISSUE TITLE
有关The Intervention Constraint Module的思考和问题

### ISSUE THREAD

**Issue by destiny199511** [dgliu/KDD23_EFIN#4]
您好，</p> 读完这篇paper后，对于The Intervention Constraint Module这部分有一些思考（不知道合理与否），还想请教解答下。 
           </p> 首先，文中提及的增加treatment inverse label的loss是为了做干扰约束，平衡消除掉**向量e<sup>xt</sup>中学习到的treatment倾向信息**，不知道这样理解对不对？
           </p> 其次，假如理解正确，是否可以将之类比于引入倾向性得分(propensity score)，进而**逆概加权**(inverse probability weighting, IPW)？文中的操作是更关注到向量e<sup>xt</sup>的学习，而一般的逆概加权是在于模型参数的学习。
           </p> 最后，还是假如上述成立，那么是否尝试过，treatment label不做inverse而是**shuffle/random**，效果是否下降或一致呢？
           </p> 多谢！

**Comment by dgliu** [comment]
> 您好，
> 
> 读完这篇paper后，对于The Intervention Constraint Module这部分有一些思考（不知道合理与否），还想请教解答下。
> 首先，文中提及的增加treatment inverse label的loss是为了做干扰约束，平衡消除掉**向量ext中学习到的treatment倾向信息**，不知道这样理解对不对？
> 其次，假如理解正确，是否可以将之类比于引入倾向性得分(propensity score)，进而**逆概加权**(inverse probability weighting, IPW)？文中的操作是更关注到向量ext的学习，而一般的逆概加权是在于模型参数的学习。
> 最后，还是假如上述成立，那么是否尝试过，treatment label不做inverse而是**shuffle/random**，效果是否下降或一致呢？
> 多谢！

你好，感谢你对我们工作的关注。

1. 你的理解是对的；
2. 是的，本质上都是期望解决数据选择偏置，只是视角不一样。除了这两者之外，还有许多其他类型的约束操作，例如约束两个group之间的MMD等；
3. 在二元treatment情况下，shuffle/random等价于对部分实例做干扰约束，而inverse是全部实例做干预约束，前者的效果经过良好调参应该有空间更好；在多元treatment情况下，为了避免枚举所有的inverse，在除自身treatment label外shuffle/random，是一个实践中推荐的操作。

祝好，
