### ISSUE TITLE
关于多维度多值干预以及Dragnet处理多值干预的疑问

### ISSUE THREAD

**Issue by lyzltysgithub** [dgliu/KDD23_EFIN#5]
老师您好！
看到原文中，t是向量，t=[ti0,ti1,ti1,...,tidt]，其中ti0是是treatment的ID，我理解更general的模型，是可以进行多维度、多值干预的吗？比如我要决策1.发哪种券（立减、满减、随单补）2.各种券分别发多少钱？可能还会有3.券的有效时间等多维度Treatment？我看了closed掉的issue，大概知道了多值干预如何处理？那么如果是原论文中的多维度、多值干预该如何处理呢？

另外我在您的实验部分看到您对比了Dragonnet多值干预情况，是只对比了二值干预的情况吗？因为Dragnet改为多值干预似乎不像改TARNet和CFRNet那样简单，Dragnet的倾向性分数也是需要改成softmax吗（原作者采用的是Sigmoid函数，loss采用的是Binary Cross Entropy ），以及下图的Dragonnet中的Target Regulization如何处理？
![77081642-e7069280-6a35-11ea-8b19-b87b510e4d2a](https://github.com/user-attachments/assets/5d147cb6-6eda-4df1-8fd0-1bae892866fa)
期待您的回复！

**Comment by lyzltysgithub** [comment]
关于多维度干预，我理解是要把各种干预进行排列组合，那么ID的总数K=treat1_num * treat2_num *treat3_num ....吗？这样的话倾向性分数该如何计算呢

**Comment by dgliu** [comment]
> 老师您好！ 看到原文中，t是向量，t=[ti0,ti1,ti1,...,tidt]，其中ti0是是treatment的ID，我理解更general的模型，是可以进行多维度、多值干预的吗？比如我要决策1.发哪种券（立减、满减、随单补）2.各种券分别发多少钱？可能还会有3.券的有效时间等多维度Treatment？我看了closed掉的issue，大概知道了多值干预如何处理？那么如果是原论文中的多维度、多值干预该如何处理呢？
> 
> 另外我在您的实验部分看到您对比了Dragonnet多值干预情况，是只对比了二值干预的情况吗？因为Dragnet改为多值干预似乎不像改TARNet和CFRNet那样简单，Dragnet的倾向性分数也是需要改成softmax吗（原作者采用的是Sigmoid函数，loss采用的是Binary Cross Entropy ），以及下图的Dragonnet中的Target Regulization如何处理？ ![77081642-e7069280-6a35-11ea-8b19-b87b510e4d2a](https://private-user-images.githubusercontent.com/82942288/396391176-5d147cb6-6eda-4df1-8fd0-1bae892866fa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ2ODE4MjUsIm5iZiI6MTczNDY4MTUyNSwicGF0aCI6Ii84Mjk0MjI4OC8zOTYzOTExNzYtNWQxNDdjYjYtNmVkYS00ZGYxLThmZDAtMWJhZTg5Mjg2NmZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIwVDA3NTg0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM3YWFkMzRiMGFiMjE4OWZhZjI4ZjY5N2I4YmY0ZGJkYWVhZmYwNDM2NWMzZjI3YzczMTc0ZmQzNDcwMWE5N2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.xAPcs6--HaCeL-g9X4_AiOkq5FNi5WhejmhjQS1_WgU) 期待您的回复！

你好，感谢你对我们工作的关注。

在实际处理中，我们可以将一系列不同干预赋予索引ID，然后将每个干预对应的特征信息作为向量的其余维度。这意味着不会存在有相同索引ID且不同特征信息的情况，每个t都能唯一标识多值干预的一种，在缺少特征信息的情况下就退化为传统的只用ID来区分干预的设置。你可能可以再思考一下你表述的多维度、多值干预的处理过程。

对于二值干预架构的多值扩展，一个简单的处理就是构建多个二值干预架构，每次分别将某种干预的标签置为1，其余置为0，基本上不需要修改原本架构的计算过程。
